### ISSUE TITLE
Current template has no filename

### ISSUE THREAD

**Issue by johnnyfreeman** [segmentio/metalsmith-templates#12]
Hey there! I'm very new to the world of Metalsmith. I'm getting this error:

```
Error: Cannot extend "layout.html" because current template has no filename.
```

Here's my [build file](https://github.com/vovn/vovn.github.io/blob/feature/metalsmith/build.js) and my [source files](https://github.com/vovn/vovn.github.io/tree/feature/metalsmith/src).

I have gone through the docs for Metalsmith, Metalsmith-templates, Consolidate.js, Swig; and cannot see what I'm doing wrong.

I have, however, found a  temporary solution for my problem in changing [line 55](https://github.com/segmentio/metalsmith-templates/blob/master/lib/index.js#L55) of this plugin to:

```javascript
var tmpl = file;
```

Any ideas what I might be doing wrong? Or have I stumbled onto a bug? Thanks!

**Comment by ianstormtaylor** [comment]
Hey thanks for this sorry for the delay. Now that https://github.com/superwolff has split out this plugin into two separate plugins—[layouts](https://github.com/superwolff/metalsmith-layouts) and [in-place](https://github.com/superwolff/metalsmith-in-place)—I'm going to deprecate the `metalsmith-templates` plugin, so that we can use the simpler ones instead. I'm going to close this PR, but feel free to re-open there!

Added a deprecation notice to the [readme](https://github.com/segmentio/metalsmith-templates/blob/master/Readme.md).
