### ISSUE TITLE
Unable to register template helper in json

### ISSUE THREAD

**Issue by carlosanunes** [segmentio/metalsmith-templates#16]
Hi,

I seem unable to register a handlebars helper in a json. Although the helper is registered it does not call the specified function, it only prints the "function name".

This is the syntax I am using :

    "metalsmith-templates": {
        "engine": "handlebars",
        "helpers" : { "<helper_name>" : "<function_name>" }
    }

**Comment by ianstormtaylor** [comment]
Hey thanks for this sorry for the delay. Now that https://github.com/superwolff has split out this plugin into two separate plugins—[layouts](https://github.com/superwolff/metalsmith-layouts) and [in-place](https://github.com/superwolff/metalsmith-in-place)—I'm going to deprecate the `metalsmith-templates` plugin, so that we can use the simpler ones instead. I'm going to close this PR, but feel free to re-open there!

Added a deprecation notice to the [readme](https://github.com/segmentio/metalsmith-templates/blob/master/Readme.md).
