### ISSUE TITLE
Pass an instance of a consolidate engine

### ISSUE THREAD

**Issue by garygreen** [segmentio/metalsmith-templates#23]
At the moment it doesn't appear possible to set custom settings on the consolidated engine, as it creates the engine based on the string you give it. It would be good if it could detect if you passed it a function and use that instead of creating the engine.

For example:

Currently only allows the below (which causes issues in not being able to e.g. add ejs filters)

    .use(templates({ engine: 'ejs' });

It might be possible to do something like the below (though this looks messy, is there a better alternative?)
 
    var consolidate = require('consolidate');
    consolidate.requires.ejs = require('ejs');
    consolidate.requires.ejs.filters.url = function() { };
    .use(templates({ engine: consolidate.requires.ejs });

**Update** it doesn't look like the above example would be possible as consolidate doesn't expose the `requires` -- I'm not sure there is any way around this?

**Comment by fsbdev** [comment]
@andrezero it is setting it directly on the Handlbars object - since the nodejs `require` caches modules, what you set on that Handlerbars object will still be there when consolidate requires it.
Unfortunately this means your example would not work if you used a separate Handlebars instance like `Handlebars.create()`.

**Comment by robertdodd** [comment]
You can play with Handlebars anytime after requiring it:

    var Metalsmith  = require('metalsmith'),
        markdown    = require('metalsmith-markdown'),
        templates   = require('metalsmith-templates'),
        Handlebars  = require('handlebars');

    Handlebars.registerHelper('ifEq', function(v1, v2, options) {
      if (v1 === v2) {
        return options.fn(this);
      }
      return options.inverse(this);
    });

    Metalsmith(__dirname)
        .use(...)
        ...

Can you access the other templating engines the same way?

**Comment by ianstormtaylor** [comment]
Hey thanks for this sorry for the delay. Now that https://github.com/superwolff has split out this plugin into two separate plugins—[layouts](https://github.com/superwolff/metalsmith-layouts) and [in-place](https://github.com/superwolff/metalsmith-in-place)—I'm going to deprecate the `metalsmith-templates` plugin, so that we can use the simpler ones instead. I'm going to close this PR, but feel free to re-open there!

Added a deprecation notice to the [readme](https://github.com/segmentio/metalsmith-templates/blob/master/Readme.md).
