### ISSUE TITLE
Why limit to only templates directory? 

### ISSUE THREAD

**Issue by simplyeffectiveweb** [segmentio/metalsmith-templates#24]
An advantage of Metalsmith is that it looks at every file, and the developer is free with structure.

However, this plugin does not make that possible  (and therefore limits Metalsmith) because it only looks in a single defined directory. In some case the user is forced to make a template per page in the 'templates' folder, rather than a genral layout template and further page templates in an 'src' folder (and including markdown as partials). So far this seems standard in other static site generators I've tried.

I don't really see the point in having the directory option. Why not enable the user to put templates wherever, and continue the Metalsmith trend of freedom with structure? (and I realise this plugin is developed by the Metalsmith developer, which makes this a surprising choice of function)

Shame as this just brought my use of Metalsmith to a stop, and all was going great before that.

**Comment by mayo** [comment]
In theory, you should be able to keep templates along with your content though. Just point the `templates` option at your source directory, and it will be so. You'll have to work around getting markdown and other plugins to ignore your templates (you don't want your templates processed by content plugins, right?) and probably keep your content files from being processed by the template engine (whichever you choose). You could most likely use the `branch` plugin for this, although the result will be quite messy, imho.

Btw, having to create page-specific templates is a shortcoming of the templating engine, rather than the plugin. Have a look at templating engines like Swig or Jade that support inheritance. Although I do agree that treating content files as templates has its benefits and is useful on its own, keeping actual layout templates in separate location has it's merits. (See #22 and [mayo/metalsmith-templates](https://github.com/mayo/metalsmith-templates).)

Every fork links to its origin, so it's relatively simple to track things back. Unless you have a specific need or instructions to use a fork of a Metalsmith plugin, you should use the original. When you do need to use a fork, you don't need to install the plugins separately/system wide. You can specify the github repo in your `package.json` file and `npm install` will take care of things in your module/project.

**Comment by simplyeffectiveweb** [comment]
@mayo Thanks for the various bits of info you've provided here and in other related threads.

I've come to the conclusion that half my battle is because of Handlebars and it's attempt to be logic-less. I should have read the background to it first. Personally, for me a bringing in the results of a function (Handlebars) compared to a for loop in the template (jade, eco, swig, etc) is not more or less logic based. 

Probably Handlebars would shine within a multi-language system, But I now see that all I was doing was populating my build.js (or any other js helper file, with template specific code). So I would rather that went in the template (especially a template for a static site generator, which by nature is the source of the actual template).

Thanks for the info whcih led to my push towards swig.

**Comment by ianstormtaylor** [comment]
Hey thanks for this sorry for the delay. Now that https://github.com/superwolff has split out this plugin into two separate plugins—[layouts](https://github.com/superwolff/metalsmith-layouts) and [in-place](https://github.com/superwolff/metalsmith-in-place)—I'm going to deprecate the `metalsmith-templates` plugin, so that we can use the simpler ones instead. I'm going to close this PR, but feel free to re-open there!

Added a deprecation notice to the [readme](https://github.com/segmentio/metalsmith-templates/blob/master/Readme.md).
