### ISSUE TITLE
Document default values of options

### ISSUE THREAD

**Issue by tmcw** [segmentio/metalsmith-templates#40]
The [readme shows how to configure options](https://github.com/segmentio/metalsmith-templates#javascript-usage), but what are the values if you don't?

**Comment by ianstormtaylor** [comment]
Hey thanks for this sorry for the delay. Now that https://github.com/superwolff has split out this plugin into two separate plugins—[layouts](https://github.com/superwolff/metalsmith-layouts) and [in-place](https://github.com/superwolff/metalsmith-in-place)—I'm going to deprecate the `metalsmith-templates` plugin, so that we can use the simpler ones instead. I'm going to close this issue, but feel free to re-open there!

Added a deprecation notice to the [readme](https://github.com/segmentio/metalsmith-templates/blob/master/Readme.md).
