### ISSUE TITLE
Add ability to specify parent templates

### ISSUE THREAD

**Issue by muchweb** [segmentio/metalsmith-templates#43]
**Proposal:** add ability to specify parent templates

As a user, I want to be able to specify *parent templates* for other templates. This is not the same as partials. This functionality already comes as standard in Jeykull as I would expect to have this built-in to templates module.

**Example:**

1. `src/post1.md`:

  ```markdown
  ---
  title: My post
  template: post.hbs
  ---
  Hello
  ```

2. `templates/post.hbs`:

  ```html
  ---
  template: html.hbs
  ---
  <h1>{{title}}</h1>
  <p>{{contents}}</p>
  ```

3. `templates/html.hbs`:

  ```html
  <!doctype html>
  <html lang="en">
  <head>
      <meta charset="UTF-8" />
      <title>{{title}}</title>
  </head>
  <body>
      {{{contents}}}
  </body>
  </html>
  ```

4. Expected output:

  ```html
  <!doctype html>
  <html lang="en">
  <head>
      <meta charset="UTF-8" />
      <title>My post</title>
  </head>
  <body>
      <h1>My post</h1>
      <p>Hello</p>
  </body>
  </html>
  ```

Maybe related: https://github.com/segmentio/metalsmith-templates/pull/27, https://github.com/segmentio/metalsmith-templates/pull/26, https://github.com/segmentio/metalsmith-templates/pull/21

**Comment by ianstormtaylor** [comment]
Hey thanks for this sorry for the delay. Now that https://github.com/superwolff has split out this plugin into two separate plugins—[layouts](https://github.com/superwolff/metalsmith-layouts) and [in-place](https://github.com/superwolff/metalsmith-in-place)—I'm going to deprecate the `metalsmith-templates` plugin, so that we can use the simpler ones instead. I'm going to close this issue, but feel free to re-open there!

Added a deprecation notice to the [readme](https://github.com/segmentio/metalsmith-templates/blob/master/Readme.md).
