### ISSUE TITLE
Error: Uses a non existing method 'path'

### ISSUE THREAD

**Issue by mxlv** [segmentio/metalsmith-templates#45]
So I get this error message

```
...\node_modules\metalsmith-templates\lib\index.js:77
        str = metalsmith.path(dir, data.template || def);
                         ^
TypeError: Object #<Metalsmith> has no method 'path'
    at convert (...\node_modules\metalsmith-templates\lib\index.js:77:26)
```

I fixed it by changing line 77 to:
```
str = metalsmith.join(dir, data.template || def);
```

Anybody else has this issue?

**Comment by ianstormtaylor** [comment]
Hey thanks for this sorry for the delay. Now that https://github.com/superwolff has split out this plugin into two separate plugins—[layouts](https://github.com/superwolff/metalsmith-layouts) and [in-place](https://github.com/superwolff/metalsmith-in-place)—I'm going to deprecate the `metalsmith-templates` plugin, so that we can use the simpler ones instead. I'm going to close this issue, but feel free to re-open there!

Added a deprecation notice to the [readme](https://github.com/segmentio/metalsmith-templates/blob/master/Readme.md).
