### ISSUE TITLE
Pull requests left hanging?

### ISSUE THREAD

**Issue by pikeas** [segmentio/metalsmith-templates#47]
Seems like several useful pull requests have been left unmerged for quite some time...any reason they haven't been merged or closed?

**Comment by paazmaya** [comment]
I am interested to hear the reasons too...

**Comment by JimmyMultani** [comment]
Hey @ianstormtaylor, can you please look into this? Seems like the README could use an update as well. Some contributors have made pull requests as well.

Thanks!

**Comment by joakim** [comment]
In general, what's the status of this project? It looks to me like it's abandoned/neglected, and there's a number of interesting PRs that are left hanging…

**Comment by chrismbeckett** [comment]
Yeah, it sure seems dead. Too bad, this was a great framework compared to Jeykll. Maybe it needs a community fork to breathe some new life into it?

**Comment by ianstormtaylor** [comment]
Hey thanks for this sorry for the delay. Now that https://github.com/superwolff has split out this plugin into two separate plugins—[layouts](https://github.com/superwolff/metalsmith-layouts) and [in-place](https://github.com/superwolff/metalsmith-in-place)—I'm going to deprecate the `metalsmith-templates` plugin, so that we can use the simpler ones instead. I'm going to close this issue, but feel free to re-open there!

Added a deprecation notice to the [readme](https://github.com/segmentio/metalsmith-templates/blob/master/Readme.md).
