### ISSUE TITLE
Allow specifying file extension transformation

### ISSUE THREAD

**Issue by drinchev** [segmentio/metalsmith-templates#51]
Hey there,

I was having difficulties with creating a blog that has it's templates with `.hbs` extension.

Namely I have the following directory structure and code :

```
{
  "source": "./pages",
  "plugins": {
    "metalsmith-templates": {
      "engine": "handlebars"
    },
    "metalsmith-permalinks": {
      "pattern": ":title"
    }
  }
}
```

files : 

```
    pages/index.hbs
```

The final output is :

```
    build/index.hbs
```

which IMHO is a bit wrong. 

Don't you think there should be a configuration property, specifying the destination extension name?

I believe it's far better if your templates have `.hbs` extension than `.html`. 

Thanks.

**Comment by ianstormtaylor** [comment]
Hey thanks for this sorry for the delay. Now that https://github.com/superwolff has split out this plugin into two separate plugins—[layouts](https://github.com/superwolff/metalsmith-layouts) and [in-place](https://github.com/superwolff/metalsmith-in-place)—I'm going to deprecate the `metalsmith-templates` plugin, so that we can use the simpler ones instead. I'm going to close this issue, but feel free to re-open there!

Added a deprecation notice to the [readme](https://github.com/segmentio/metalsmith-templates/blob/master/Readme.md).
