### ISSUE TITLE
Support for react.js?

### ISSUE THREAD

**Issue by jamiecollinson** [segmentio/metalsmith-templates#52]
As metalsmith-templates makes use of consolidate.js I thought it should work with react.js as that's officially supported:

https://www.npmjs.com/package/consolidate

However I can't get it to work, and get a TypeError on build:
```
TypeError: undefined is not a function
```
Has anyone got this working? I know there are separate projects for react (https://github.com/coodoo/metalsmith-reactjs & https://github.com/yeojz/metalsmith-react-templates) but I've found both of them out of date with the latest versions of react (>0.13).

**Comment by LnL7** [comment]
You have to update the version of consolidate, you could install the latest version from git with `npm install tj/consolidate.js`

**Comment by ianstormtaylor** [comment]
Hey thanks for this sorry for the delay. Now that https://github.com/superwolff has split out this plugin into two separate plugins—[layouts](https://github.com/superwolff/metalsmith-layouts) and [in-place](https://github.com/superwolff/metalsmith-in-place)—I'm going to deprecate the `metalsmith-templates` plugin, so that we can use the simpler ones instead. I'm going to close this issue, but feel free to re-open there!

Added a deprecation notice to the [readme](https://github.com/segmentio/metalsmith-templates/blob/master/Readme.md).
