### ISSUE TITLE
Nunjucks issues

### ISSUE THREAD

**Issue by dfcreative** [segmentio/metalsmith-templates#55]
Using nunjucks template engine with metalsmith causes 2 issues:
- Nunjucks needs to be configured via `nunjucks.config(dir)` (http://mozilla.github.io/nunjucks/api.html). For now setting `"directory": "./templates"` in _metalsmith.json_ does nothing - templates still need full path in extend `{% extend "./templates/base.html" %}`
- Metalsmith process doesn’t exit after successfully built.

**Comment by dfcreative** [comment]
To solve both issues, nunjucks need to be configured like so:
```js
nunjucks.configure('./templates', {watch: false})
```

**Comment by eddywashere** [comment]
@dfcreative do you happen to know how to register filters for nunjucks and metalsmith? I can't seem to add it to the current env.

**Comment by dfcreative** [comment]
@eddywashere I came up that it is easier and more flexible to setup build via gulp than any static generator. Also it seems metalsmith stuff is no more supported by devs.

**Comment by ianstormtaylor** [comment]
Hey thanks for this sorry for the delay. Now that https://github.com/superwolff has split out this plugin into two separate plugins—[layouts](https://github.com/superwolff/metalsmith-layouts) and [in-place](https://github.com/superwolff/metalsmith-in-place)—I'm going to deprecate the `metalsmith-templates` plugin, so that we can use the simpler ones instead. I'm going to close this issue, but feel free to re-open there!

Added a deprecation notice to the [readme](https://github.com/segmentio/metalsmith-templates/blob/master/Readme.md).
